---
abstract: 'Provides an interface to smartctl to return disk stats and to run tests.'
author:
  - 'Paul Trost <ptrost@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::Fatal: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142690'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Disk-SMART
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Math::Round: '0'
  perl: '5.010'
resources:
  repository: https://github.com/paultrost/Disk-SMART-Perl.git
version: '0.09'
x_clean:
  FILES: Disk-SMART-*
x_dist:
  COMPRESS: 'gzip -9f'
  SUFFIX: gz
